### ISSUE TITLE
Unlockable armors have no armor points

### ISSUE THREAD

**Issue by TonisGaming** [HugoZink/lekousin-s-Armor-Overhaul#2]
They have 0 armor, yet all the other stats seem to be correct

**Comment by morerokk** [comment]
What

**Comment by morerokk** [comment]
I think this might be a mod compatibility issue, if you have other mods that change armor values by overwriting the entire table this *will* happen.

**Comment by morerokk** [comment]
Closing the issue because this was most likely related to a different conflicting mod being installed.
